# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QiPinTong' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QiPinTong

pod 'RongCloudIM/IMLib', '~> 2.8.8'
pod 'RongCloudIM/IMKit', '~> 2.8.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'MJRefresh'
pod 'FMDB'
pod 'WechatOpenSDK'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'AMapLocation'
#pod 'AMapNavi'

  target 'QiPinTongTests' do
    inherit! :search_paths

  end

  target 'QiPinTongUITests' do
    inherit! :search_paths

  end

end
